name: Feature Request
description: Suggest an idea or new feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: "I would like rdap to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
    validations:
      required: false

  - type: dropdown
    id: query-type
    attributes:
      label: Related Query Type
      description: Which query type does this feature relate to?
      options:
        - Domain
        - TLD
        - IP / CIDR
        - ASN
        - Entity
        - Nameserver
        - Configuration
        - Output / Display
        - Other
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Example Usage
      description: If applicable, provide example commands or expected output.
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request here.
    validations:
      required: false
